### ISSUE TITLE
It's just a test 

### ISSUE THREAD

**Issue by 1Estella** [Ingenico-ePayments/connect-sdk-client-android#1]
I'd like to know how I can be supported if I have trouble in developing with Ingenico terminals.

**Comment by ebomcke-ingenico** [comment]
Hi,
If you're looking for help with our terminals I'm afraid you're not in the right place. This SDK is a companion of the Connect API (Ingenico's online payment solution), it cannot be used for the Telium TETRA platform (Ingenico's smart terminal).
If you'd like to know more about developing with the Telium TETRA platform I would recommend you to go to https://developer.ingenico.com/hc/en-gb (developer portal for Telium TETRA).
Best,
Etienne Bömcke
Product Manager - Connect API & SDKs

**Comment by 1Estella** [comment]
Thanks very much for the information provided!
