### ISSUE TITLE
Is there a way to use this Sdk for flutter?

### ISSUE THREAD

**Issue by abinvs-2019** [Ingenico-ePayments/connect-sdk-client-android#11]
Have been trying a plugin but could not run the project.

**Comment by LeonStemerdink-Worldline** [comment]
Hello abinvs-2019,

While the SDK does not officially support flutter, it is possible to call SDK methods from flutter. 
If you look for "calling Android native code from flutter" you should find tutorials that explain how to setup and use `MethodChannel`. https://api.flutter.dev/flutter/services/MethodChannel-class.html

**Comment by abinvs-2019** [comment]
Yes thankyou, But how can we integrate the SDK to an existing flutter project. I could not find any docs related to that.

**Comment by abinvs-2019** [comment]
Could you help me in integrating the SDK in flutter?. Would be appreciated.
abin.tictech@gmail.com
