### ISSUE TITLE
Printer APOS A8

### ISSUE THREAD

**Issue by brdacon1** [Ingenico-ePayments/connect-sdk-client-android#13]
Hello everyone,

I'm try to communication with printer APOS A8 and not find documentation end how can I do that.

Could you share documentation and .aar file for me?

**Comment by IngenicoEPayments** [comment]
Hello brdacon1,

Thank you for reaching out.
This SDK is a general library to help with integrating online payments on the Connect platform in Native apps. It does not offer support for Point Of Sale solutions like the device you are mentioning.
For support with that device you should reach out to your contacts within Worldline.
