### ISSUE TITLE
Add support of BYN instead of BYR

### ISSUE THREAD

**Issue by Kolyall** [Ingenico-ePayments/connect-sdk-client-android#8]
/home/nick/StudioProjects/EpaymentExample/globalcollect-sdk/src/main/java/com/globalcollect/gateway/sdk/client/android/sdk/model/CurrencyCode.java

CurrencyCode `BYR,` exist
but  `BYN,` doesn't exist
https://en.wikipedia.org/wiki/Belarusian_ruble

**Comment by rob-spoor** [comment]
Since the latest release, version 5.8.0, the currency code can (and should) be given as strings (although the enums are still supported). Does that work for you?
